name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      file:
        description: "Dockerfile to build and push"
        required: true
        default: "./Dockerfile.base"
      image:
        description: "Image to build and push"
        required: true
        default: "ghcr.io/arsdever/"
      tag:
        description: "Tag to build and push with"
        required: true
        default: "latest"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: >
          ./docker.sh \
            build_push \
            ${{ github.event.inputs.file }} \
            ${{ github.event.inputs.image }} \
            ${{ github.event.inputs.tag }}
